apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: dev
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    ms: rabbitmq-deployment

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      ms: rabbitmq-deployment
  template:
    metadata:
      labels:
        ms: rabbitmq-deployment
    spec:
      containers:
      - name: rabbitmq-deployment
        image: rabbitmq
        ports:
        - containerPort: 5672